### ISSUE TITLE
putting all codes into a jupyter notebook

### ISSUE THREAD

**Issue by sankopay** [arekmula/robot_localization#3]
hello there, could you guide me on how i can use this in a jupyter notebook? i want to put together all the codes in a notebook and i really dont know know how

**Comment by arekmula** [comment]
Hello,
This will be possible only if Jupyter Notebook can use Tkinter. If it can then you just need to put all the files from the repository to separate blocks. 

Thie first block should be created from "graphics.py". If the "test" function from this file work, then the whole project will probably also work. 
The second block should be created from the "gridutil.py" file.
The third block should be created from the "agents/prob.py" file. You should remove unnecessary import from line 7.
The last block should be created from the main.py file where all is put into one piece. You should start with deleting imports from lines 12, 13, and 15. Then change line 218 to "agent = LocAgent(env.size, env.walls, eps_perc, eps_move)". 

You will also need to install some of the additional packages such as numpy and pgmpy.

**Comment by sankopay** [comment]
the first part from "graphics" works fine and opens a new window named graphics window and then there's a saying "centered text" but i dont know what i should put as input there??? because every entry returns "Sample!" and then when i close the window, it gives an error in the jupyter cell... and also what contribution aka change in this code can make it more different that it is now, but still makes it fall into the category of "reinforcement learning"?? 
btw could you please kindly explain the functions happened in each cell or file? like a brief explanation would do.

thanks for replying back so soon though.

**Comment by arekmula** [comment]
Try to comment lines 
```
update()

if __name__ == "__main__":
    test()
```

If you want to make some changes in this code to make it different you can try changing the represented state space. I mean instead of predicting position with the orientation you can try to predict only position.  You can also change observations returned from robot. For example, the robot can only return information if it detects an obstacle in front of it.

The graphics.py file is responsible for displaying the robot with the world on the screen (When I say robot I mean arrow). 
The gridutil.py file is responsible for functions for navigating square 2d grids. Like predict next position, based on the current one, robot's orientation and robot's next move.
The prob.py file is file where all the "reinforcement learning" magic happens. It's a file where all functions related to state space and actions are defined.
The main.py file is a place where all previously defined functions are called to make it 1 system.
